export const ETHEREUM_PRIMARY_RPC_ADAPTER = Symbol('ETHEREUM_PRIMARY_RPC_ADAPTER');
export const ETHEREUM_FALLBACK_RPC_ADAPTER = Symbol('ETHEREUM_FALLBACK_RPC_ADAPTER');
export const SOLANA_PRIMARY_RPC_ADAPTER = Symbol('SOLANA_PRIMARY_RPC_ADAPTER');
export const SOLANA_FALLBACK_RPC_ADAPTER = Symbol('SOLANA_FALLBACK_RPC_ADAPTER');
export const TRON_PRIMARY_RPC_ADAPTER = Symbol('TRON_PRIMARY_RPC_ADAPTER');
export const TRON_FALLBACK_RPC_ADAPTER = Symbol('TRON_FALLBACK_RPC_ADAPTER');
