export type NodeEnv = 'development' | 'test' | 'production';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export type AppConfig = {
  readonly appVersion: string;
  readonly nodeEnv: NodeEnv;
  readonly port: number;
  readonly logLevel: LogLevel;
  readonly telegramEnabled: boolean;
  readonly chainWatcherEnabled: boolean;
  readonly solanaWatcherEnabled: boolean;
  readonly tronWatcherEnabled: boolean;
  readonly chainReceiptConcurrency: number;
  readonly chainRpcMinIntervalMs: number;
  readonly chainBackoffBaseMs: number;
  readonly chainSolanaBackoffBaseMs: number;
  readonly chainBackoffMaxMs: number;
  readonly chainBlockQueueMax: number;
  readonly chainSolanaQueueMax: number;
  readonly chainTronQueueMax: number;
  readonly chainSolanaCatchupBatch: number;
  readonly chainTronCatchupBatch: number;
  readonly chainSolanaPollIntervalMs: number;
  readonly chainTronPollIntervalMs: number;
  readonly chainHeartbeatIntervalSec: number;
  readonly chainReorgConfirmations: number;
  readonly botToken: string | null;
  readonly databaseUrl: string;
  readonly ethAlchemyWssUrl: string | null;
  readonly ethInfuraWssUrl: string | null;
  readonly solanaHeliusHttpUrl: string | null;
  readonly solanaHeliusWssUrl: string | null;
  readonly solanaPublicHttpUrl: string | null;
  readonly solanaPublicWssUrl: string | null;
  readonly tronPrimaryHttpUrl: string | null;
  readonly tronFallbackHttpUrl: string | null;
  readonly uniswapSwapAllowlist: readonly string[];
  readonly ethCexAddressAllowlist: readonly string[];
  readonly etherscanTxBaseUrl: string;
  readonly etherscanApiBaseUrl: string;
  readonly etherscanApiKey: string | null;
  readonly tronGridApiBaseUrl: string;
  readonly tronGridApiKey: string | null;
  readonly tronscanTxBaseUrl: string;
  readonly coingeckoApiBaseUrl: string;
  readonly coingeckoTimeoutMs: number;
  readonly priceCacheMaxEntries: number;
  readonly priceCacheFreshTtlSec: number;
  readonly priceCacheStaleTtlSec: number;
  readonly chainMaxLagWarn: number;
  readonly chainMaxQueueWarn: number;
  readonly chainMaxBackoffWarnMs: number;
  readonly alertMinSendIntervalSec: number;
  readonly tokenMetaCacheTtlSec: number;
  readonly historyCacheTtlSec: number;
  readonly historyRateLimitPerMinute: number;
  readonly historyButtonCooldownSec: number;
  readonly historyStaleOnErrorSec: number;
};
