export type NodeEnv = 'development' | 'test' | 'production';

export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

export type AppConfig = {
  readonly appVersion: string;
  readonly nodeEnv: NodeEnv;
  readonly port: number;
  readonly logLevel: LogLevel;
  readonly telegramEnabled: boolean;
  readonly tmaEnabled: boolean;
  readonly chainWatcherEnabled: boolean;
  readonly solanaWatcherEnabled: boolean;
  readonly tronWatcherEnabled: boolean;
  readonly chainReceiptConcurrency: number;
  readonly chainRpcMinIntervalMs: number;
  readonly chainBackoffBaseMs: number;
  readonly chainSolanaBackoffBaseMs: number;
  readonly chainBackoffMaxMs: number;
  readonly chainBlockQueueMax: number;
  readonly chainSolanaQueueMax: number;
  readonly chainTronQueueMax: number;
  readonly chainSolanaCatchupBatch: number;
  readonly chainTronCatchupBatch: number;
  readonly chainSolanaPollIntervalMs: number;
  readonly chainTronPollIntervalMs: number;
  readonly chainHeartbeatIntervalSec: number;
  readonly chainReorgConfirmations: number;
  readonly botToken: string | null;
  readonly tmaBaseUrl: string | null;
  readonly tmaBotUsername: string | null;
  readonly tmaAllowedOrigins: readonly string[];
  readonly databaseUrl: string;
  readonly ethAlchemyWssUrl: string | null;
  readonly ethInfuraWssUrl: string | null;
  readonly solanaHeliusHttpUrl: string | null;
  readonly solanaHeliusWssUrl: string | null;
  readonly solanaPublicHttpUrl: string | null;
  readonly solanaPublicWssUrl: string | null;
  readonly tronPrimaryHttpUrl: string | null;
  readonly tronFallbackHttpUrl: string | null;
  readonly uniswapSwapAllowlist: readonly string[];
  readonly ethCexAddressAllowlist: readonly string[];
  readonly etherscanTxBaseUrl: string;
  readonly etherscanApiBaseUrl: string;
  readonly etherscanApiKey: string | null;
  readonly tronGridApiBaseUrl: string;
  readonly tronGridApiKey: string | null;
  readonly tronscanTxBaseUrl: string;
  readonly coingeckoApiBaseUrl: string;
  readonly coingeckoTimeoutMs: number;
  readonly priceCacheMaxEntries: number;
  readonly priceCacheFreshTtlSec: number;
  readonly priceCacheStaleTtlSec: number;
  readonly chainMaxLagWarn: number;
  readonly chainMaxQueueWarn: number;
  readonly chainMaxBackoffWarnMs: number;
  readonly alertMinSendIntervalSec: number;
  readonly tokenMetaCacheTtlSec: number;
  readonly historyCacheTtlSec: number;
  readonly historyRateLimitPerMinute: number;
  readonly historyButtonCooldownSec: number;
  readonly historyStaleOnErrorSec: number;
  readonly historyHotCacheEnabled: boolean;
  readonly historyHotCacheTopWallets: number;
  readonly historyHotCacheRefreshIntervalSec: number;
  readonly historyHotCachePageLimit: number;
  readonly historyHotCacheMaxItemsPerWallet: number;
  readonly historyHotCacheTtlSec: number;
  readonly historyHotCacheStaleSec: number;
  readonly metricsEnabled: boolean;
  readonly rateLimitEtherscanMinTimeMs: number;
  readonly rateLimitEtherscanMaxConcurrent: number;
  readonly rateLimitSolanaHeliusMinTimeMs: number;
  readonly rateLimitSolanaHeliusMaxConcurrent: number;
  readonly rateLimitSolanaPublicMinTimeMs: number;
  readonly rateLimitSolanaPublicMaxConcurrent: number;
  readonly rateLimitTronGridMinTimeMs: number;
  readonly rateLimitTronGridMaxConcurrent: number;
  readonly rateLimitTronPublicMinTimeMs: number;
  readonly rateLimitTronPublicMaxConcurrent: number;
  readonly rateLimitCoingeckoMinTimeMs: number;
  readonly rateLimitCoingeckoMaxConcurrent: number;
  readonly rateLimitEthRpcMinTimeMs: number;
  readonly rateLimitEthRpcMaxConcurrent: number;
  readonly jwtSecret: string | null;
  readonly jwtAccessTtlSec: number;
  readonly jwtRefreshTtlSec: number;
};
